// swift-tools-version: 6.0
import Foundation
import PackageDescription

// ServerGlass for macOS.
//
// Built as a SwiftPM executable rather than an Xcode project so the whole thing builds from the
// command line and in CI. Shipping to the App Store later means wrapping this in a bundle target;
// nothing here has to change for that.
//
// Build the Rust side first — `../../scripts/build-macos.sh` does both halves in order.

// Absolute, derived from this manifest's own location. A relative `-L` does not work: the linker
// runs with a working directory of SwiftPM's choosing, not the package root.
// Set SG_PROFILE=release to link the optimised Rust build.
private let packageDir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
private let profile = ProcessInfo.processInfo.environment["SG_PROFILE"] ?? "debug"
let workspaceTarget =
    packageDir.appendingPathComponent("../../target/\(profile)").standardizedFileURL.path

let package = Package(
    name: "ServerGlass",
    platforms: [.macOS(.v14)],
    targets: [
        // The C ABI of the Rust static library, as generated by uniffi-bindgen.
        .systemLibrary(
            name: "sg_ffiFFI",
            path: "Sources/ServerGlassFFI/generated"
        ),

        // The generated Swift wrapper. Regenerate with scripts/build-macos.sh; never edit by hand.
        .target(
            name: "ServerGlassFFI",
            dependencies: ["sg_ffiFFI"],
            path: "Sources/ServerGlassFFI",
            sources: ["generated/sg_ffi.swift"],
            linkerSettings: [
                .unsafeFlags(["-L\(workspaceTarget)", "-lsg_ffi"]),
                // russh's crypto backend and the keychain reach into these.
                .linkedFramework("Security"),
                .linkedFramework("CoreFoundation"),
                .linkedLibrary("resolv"),
            ]
        ),

        .executableTarget(
            name: "ServerGlass",
            dependencies: ["ServerGlassFFI"],
            path: "Sources/ServerGlass"
        ),
    ]
)
