//! The batch wire protocol.
//!
//! A tick's worth of requests is compiled into one `/bin/sh` script, written to a single long-lived
//! channel, and the framed reply is parsed back into [`Responses`]. One round trip, however many
//! requests.
//!
//! # Framing
//!
//! Each request is wrapped in markers carrying a per-connection random nonce:
//!
//! ```text
//! \n<nonce>B<id>\n
//! ...raw output...
//! \n<nonce>E<id> <exit code>\n
//! ```
//!
//! and the batch is terminated by `\n<nonce>Z\n`.
//!
//! The nonce is what makes this safe. Without it, `cat`ing a file that happened to contain the end
//! marker would truncate the frame — and on a monitoring tool, the file being read is often a log
//! written by someone else. A monitored host cannot predict a nonce generated by the client after
//! the connection came up, so it cannot forge a frame boundary.
//!
//! The `\n` before each marker is emitted by us, not by the command, so output lacking a trailing
//! newline cannot run into the marker. Decoding strips exactly that one byte back off.

use sg_model::{Request, Response, Responses};

use crate::quote::{shell_join, shell_quote};

/// Compiles requests into shell script and parses framed replies.
#[derive(Clone, Debug)]
pub struct Framing {
    nonce: String,
}

impl Framing {
    /// `nonce` must be unguessable by the monitored host and free of shell metacharacters and
    /// whitespace. [`crate::session::SshSession`] generates it from the OS random source.
    pub fn new(nonce: impl Into<String>) -> Self {
        Framing {
            nonce: nonce.into(),
        }
    }

    fn begin(&self, id: &str) -> String {
        format!("\n{}B{}\n", self.nonce, id)
    }

    fn end_prefix(&self, id: &str) -> String {
        format!("\n{}E{} ", self.nonce, id)
    }

    /// Marks the end of a batch.
    pub fn terminator(&self) -> String {
        format!("\n{}Z\n", self.nonce)
    }

    /// The shell command that produces a request's raw bytes.
    ///
    /// `--` stops option parsing so a path beginning with `-` is treated as a path. stderr is
    /// discarded because a missing `/proc` file is an expected outcome, reported through the exit
    /// code, not a condition worth relaying.
    fn command_for(&self, request: &Request) -> Option<String> {
        match request {
            Request::ReadFile { path } => Some(format!("cat -- {}", shell_quote(path))),
            Request::ReadDir { path } => Some(format!("ls -1 -- {}", shell_quote(path))),
            Request::Exec { argv } if !argv.is_empty() => Some(shell_join(argv)),
            // Empty argv would emit an empty command whose exit status is the *previous*
            // command's, silently corrupting the frame that follows.
            Request::Exec { .. } => None,
            // Executed by the app, never by the host.
            Request::Http { .. } => None,
        }
    }

    /// Compile a batch into one script.
    ///
    /// Returns the script and the ids it will produce frames for, in order. Requests are
    /// deduplicated by [`Request::id`], so three sources all wanting `/proc/stat` cost one `cat`.
    pub fn encode(&self, requests: &[Request]) -> (String, Vec<String>) {
        let mut script = String::new();
        let mut ids = Vec::new();

        for request in requests {
            let id = request.id();
            if ids.contains(&id) {
                continue;
            }
            let Some(command) = self.command_for(request) else {
                continue;
            };

            // Braces group the command so the redirect applies to all of it; `__sg` holds the
            // status because the printf that follows would otherwise clobber `$?`.
            script.push_str(&format!(
                "printf {}\n{{ {}; }} 2>/dev/null\n__sg=$?\nprintf {} \"$__sg\"\n",
                shell_quote(&self.begin(&id)),
                command,
                shell_quote(&format!("{}%s\n", self.end_prefix(&id))),
            ));
            ids.push(id);
        }

        script.push_str(&format!("printf {}\n", shell_quote(&self.terminator())));
        (script, ids)
    }

    /// Parse a complete framed reply.
    ///
    /// Unmatched or malformed frames are skipped rather than failing the batch: one source's
    /// request going wrong must not cost the other twenty their data for the tick. A request whose
    /// frame never arrives simply has no entry, and [`Responses::text`] returns `None` for it,
    /// which sources already treat as "this host does not have that".
    pub fn decode(&self, stream: &str) -> Responses {
        let mut responses = Responses::default();
        let mut cursor = 0usize;
        let begin_marker = format!("\n{}B", self.nonce);

        while let Some(rel) = stream[cursor..].find(&begin_marker) {
            let marker_at = cursor + rel;
            // Id runs from after the marker to the newline that closes the begin line.
            let id_start = marker_at + begin_marker.len();
            let Some(nl_rel) = stream[id_start..].find('\n') else {
                break;
            };
            let id = stream[id_start..id_start + nl_rel].to_string();
            let body_start = id_start + nl_rel + 1;

            let end_prefix = self.end_prefix(&id);
            let Some(end_rel) = stream[body_start..].find(&end_prefix) else {
                // Truncated frame — the connection dropped mid-batch. Nothing usable here.
                cursor = body_start;
                continue;
            };
            let body_end = body_start + end_rel;
            let code_start = body_end + end_prefix.len();
            let Some(code_nl) = stream[code_start..].find('\n') else {
                break;
            };
            let exit_code = stream[code_start..code_start + code_nl]
                .trim()
                .parse::<i32>()
                .unwrap_or(-1);

            responses.insert(
                id,
                Response {
                    exit_code,
                    body: stream[body_start..body_end].to_string(),
                },
            );
            cursor = code_start + code_nl + 1;
        }

        responses
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const NONCE: &str = "__SGf00dcafe__";

    fn framing() -> Framing {
        Framing::new(NONCE)
    }

    /// Simulate what the remote shell would emit for a set of frames.
    fn emit(frames: &[(&Request, i32, &str)]) -> String {
        let f = framing();
        let mut out = String::from("junk from the shell prompt");
        for (request, code, body) in frames {
            out.push_str(&f.begin(&request.id()));
            out.push_str(body);
            out.push_str(&f.end_prefix(&request.id()));
            out.push_str(&format!("{code}\n"));
        }
        out.push_str(&f.terminator());
        out
    }

    #[test]
    fn round_trips_a_single_frame() {
        let req = Request::read("/proc/stat");
        let decoded = framing().decode(&emit(&[(&req, 0, "cpu  1 2 3 4\n")]));
        assert_eq!(decoded.text(&req), Some("cpu  1 2 3 4\n"));
    }

    #[test]
    fn round_trips_many_frames_independently() {
        let stat = Request::read("/proc/stat");
        let mem = Request::read("/proc/meminfo");
        let ls = Request::read_dir("/sys/block");
        let stream = emit(&[
            (&stat, 0, "cpu 1\n"),
            (&mem, 0, "MemTotal: 8\n"),
            (&ls, 0, "sda\n"),
        ]);

        let decoded = framing().decode(&stream);
        assert_eq!(decoded.len(), 3);
        assert_eq!(decoded.text(&stat), Some("cpu 1\n"));
        assert_eq!(decoded.text(&mem), Some("MemTotal: 8\n"));
        assert_eq!(decoded.text(&ls), Some("sda\n"));
    }

    #[test]
    fn nonzero_exit_is_recorded_and_hidden_from_text() {
        let req = Request::read("/proc/pressure/cpu");
        let decoded = framing().decode(&emit(&[(&req, 1, "")]));
        // The response exists and carries the code...
        assert_eq!(decoded.get(&req).map(|r| r.exit_code), Some(1));
        // ...but `text` yields nothing, so parsers skip it without special-casing.
        assert_eq!(decoded.text(&req), None);
    }

    #[test]
    fn output_without_a_trailing_newline_is_preserved_exactly() {
        let req = Request::exec(["getconf", "CLK_TCK"]);
        let decoded = framing().decode(&emit(&[(&req, 0, "100")]));
        assert_eq!(decoded.text(&req), Some("100"));
    }

    #[test]
    fn empty_output_decodes_as_empty_not_missing() {
        let req = Request::read("/proc/empty");
        let decoded = framing().decode(&emit(&[(&req, 0, "")]));
        assert_eq!(decoded.text(&req), Some(""));
    }

    /// The reason the nonce exists: a monitored host serving content that mimics the protocol.
    #[test]
    fn payload_impersonating_frame_markers_cannot_truncate_a_frame() {
        let req = Request::read("/var/log/hostile");
        let hostile = "\n__SGE0000000000000000 0\n\n__SGB0000000000000000\nnot yours\n";
        let decoded = framing().decode(&emit(&[(&req, 0, hostile)]));
        assert_eq!(decoded.len(), 1, "hostile payload forged an extra frame");
        assert_eq!(
            decoded.text(&req),
            Some(hostile),
            "hostile payload truncated the real frame"
        );
    }

    #[test]
    fn a_truncated_final_frame_does_not_discard_earlier_ones() {
        let good = Request::read("/proc/stat");
        let cut = Request::read("/proc/meminfo");
        let f = framing();
        let mut stream = emit(&[(&good, 0, "cpu 1\n")]);
        // Connection died after the begin marker of the next frame.
        stream.push_str(&f.begin(&cut.id()));
        stream.push_str("MemTotal: 8");

        let decoded = f.decode(&stream);
        assert_eq!(decoded.text(&good), Some("cpu 1\n"));
        assert_eq!(decoded.text(&cut), None);
    }

    #[test]
    fn encode_deduplicates_repeated_requests() {
        // Three sources each independently want /proc/stat.
        let requests = vec![
            Request::read("/proc/stat"),
            Request::read("/proc/meminfo"),
            Request::read("/proc/stat"),
        ];
        let (script, ids) = framing().encode(&requests);

        assert_eq!(ids.len(), 2, "duplicate request was not merged");
        assert_eq!(script.matches("cat -- '/proc/stat'").count(), 1);
        assert_eq!(script.matches("cat -- '/proc/meminfo'").count(), 1);
    }

    #[test]
    fn encode_quotes_hostile_paths_and_argv() {
        let requests = vec![
            Request::read("/tmp/$(id)"),
            Request::exec(["docker", "inspect", "web; rm -rf /"]),
        ];
        let (script, ids) = framing().encode(&requests);

        assert_eq!(ids.len(), 2);
        assert!(script.contains("cat -- '/tmp/$(id)'"));
        assert!(script.contains("'docker' 'inspect' 'web; rm -rf /'"));
        // No unquoted injection point survived.
        assert!(!script.contains("$(id) "));
    }

    #[test]
    fn encode_skips_requests_the_host_cannot_serve() {
        let requests = vec![
            Request::get("https://example.invalid/metrics"),
            Request::Exec { argv: vec![] },
            Request::read("/proc/stat"),
        ];
        let (_script, ids) = framing().encode(&requests);
        assert_eq!(ids, vec![Request::read("/proc/stat").id()]);
    }

    #[test]
    fn encode_always_terminates_the_batch() {
        // Even an empty batch must emit the terminator, or the reader waits forever.
        let (script, ids) = framing().encode(&[]);
        assert!(ids.is_empty());
        assert!(script.contains(&format!("{NONCE}Z")));
    }

    #[test]
    fn encoded_script_is_shaped_the_way_decode_expects() {
        let req = Request::read("/proc/stat");
        let (script, _) = framing().encode(std::slice::from_ref(&req));

        // Status is captured before the trailing printf can clobber `$?`.
        let cmd_at = script.find("cat -- '/proc/stat'").expect("command present");
        let capture_at = script.find("__sg=$?").expect("status captured");
        let report_at = script.rfind("\"$__sg\"").expect("status reported");
        assert!(cmd_at < capture_at && capture_at < report_at);

        // stderr is discarded so a missing file reports via exit code, not by corrupting the body.
        assert!(script.contains("2>/dev/null"));
    }
}
