// swift-tools-version: 6.0
import Foundation
import PackageDescription

// ServerGlass apps.
//
// The manifest lives at apps/ rather than apps/macos/ because SwiftPM refuses targets outside the
// package root, and the UI target is shared with iOS under apps/shared/.
//
// Built as a SwiftPM executable rather than an Xcode project so the whole thing builds from the
// command line and in CI. `scripts/build-macos.sh` wraps the product in a bundle.
//
// The UI itself lives in ../shared/ServerGlassUI and is shared verbatim with the iOS app; only the
// app entry point and the AppKit activation dance are macOS-specific.

// Absolute, derived from this manifest's own location. A relative `-L` does not work: the linker
// runs with a working directory of SwiftPM's choosing, not the package root.
// Set SG_PROFILE=release to link the optimised Rust build.
private let packageDir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
private let profile = ProcessInfo.processInfo.environment["SG_PROFILE"] ?? "debug"
let workspaceTarget =
    packageDir.appendingPathComponent("../target/\(profile)").standardizedFileURL.path

let package = Package(
    name: "ServerGlass",
    platforms: [.macOS(.v14)],
    targets: [
        // The C ABI of the Rust static library, as generated by uniffi-bindgen.
        .systemLibrary(
            name: "sg_ffiFFI",
            path: "shared/ServerGlassFFI/generated"
        ),

        // The generated Swift wrapper. Regenerate with scripts/build-macos.sh; never edit by hand.
        .target(
            name: "ServerGlassFFI",
            dependencies: ["sg_ffiFFI"],
            path: "shared/ServerGlassFFI",
            sources: ["generated/sg_ffi.swift"],
            linkerSettings: [
                .unsafeFlags(["-L\(workspaceTarget)", "-lsg_ffi"]),
                // russh's crypto backend and the keychain reach into these.
                .linkedFramework("Security"),
                .linkedFramework("CoreFoundation"),
                .linkedLibrary("resolv"),
            ]
        ),

        // Every view, shared byte for byte with the iOS app.
        .target(
            name: "ServerGlassUI",
            dependencies: ["ServerGlassFFI"],
            path: "shared/ServerGlassUI"
        ),

        .executableTarget(
            name: "ServerGlass",
            dependencies: ["ServerGlassUI"],
            path: "macos/Sources/ServerGlassApp"
        ),
    ]
)
